<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="./public/css/index.css">
    <title>Todolist</title>
</head>
<body>
    <div class="container">
        <h2>Task Manager</h2>
        <div class="button-container">
            <button>Ajouter une tache</button>
            <form action="src/tasks/deleteAll.php" method="POST">
                <button>Effacer toutes les taches</button>
            </form>
        </div>